defaults:
  -
    scope:
      path: "HistoryOfFlash"
      type: "pages"
    values:
      layout: "default"
      author: "Sarah Murto"
      category: "Flash"
      subtitle: cats
      baseurl: /HistoryOfFlash_4662W
kramdown:
  input: GFM