defaults:
  -
    scope:
      path: "HistoryOfFlash"
      type: "pages"
    values:
      layout: "default"
      author: "Sarah Murto"
      category: "Flash"
subtitle: ""
baseurl: /HistoryOfFlash_4662W
permalink: none
title: The Rise and Fall of Flash
kramdown:
  input: GFM